### ISSUE TITLE
lua-releng: luac never see SETGLOBAL or GETGLOBAL

### ISSUE THREAD

**Issue by ssdr** [openresty/nginx-devel-utils#4]
lua-releng output:
```bash
test.lua: 0.0.1 (0.0.1)
Checking use of Lua global variables in file test.lua...
	op no.	line	instruction	args	; code
Checking line length exceeding 80...
```
my test.lua file:
```lua
local _M = { version = "0.0.1" }
function _M.test()
  local l = "local"
  g = l
  print(l, g)
  gg = {}
end
return _M
```

we can see g and gg are both gobal variables...

**Comment by agentzh** [comment]
@ssdr Weird. `lua-releng` works perfectly on my side with your `test.lua` sample:

```
$ lua-releng
test.lua: 0.0.1 (0.0.1)
Checking use of Lua global variables in file test.lua...
	op no.	line	instruction	args	; code
	2	[4]	SETGLOBAL	0 -2	; g
	5	[5]	GETGLOBAL	3 -2	; g
	8	[6]	SETGLOBAL	1 -4	; gg
Checking line length exceeding 80...
```

What version of luac is in your PATH? Mine is like this:

```
$ luac -v
Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio
```

And this is on Linux x86_64. Good luck!

**Comment by ssdr** [comment]
hey,

sorry for late reply.
my luac version:
Lua 5.2.3  Copyright (C) 1994-2013 Lua.org, PUC-Rio

by the way, it’s on Mac OSX:
Darwin localhost 14.4.0 Darwin Kernel Version 14.4.0: Thu May 28 11:35:04 PDT 2015; root:xnu-2782.30.5~1/RELEASE_X86_64 x86_64


刘 岩
Tel：18611127056
Email：ssdr_liu@163.com

"If everything seems under control, you are not going fast enough."

**Comment by agentzh** [comment]
@ssdr No, your Lua version is wrong. We require Lua 5.1 here. Lua 5.2 is a quite different language anyway and thus different bytecodes.
